export const EVENT_ADDED_REQUEST="EVENT_ADDED_REQUEST";
export const EVENT_ADDED_SUCCESS="EVENT_ADDED_SUCCESS";
export const EVENT_ADDED_FAIL="EVENT_ADDED_FAIL";
export const EVENT_REMOVE="EVENT_REMOVE";