export const EVENTSECOND_ADDED_REQUEST="EVENTSECOND_ADDED_REQUEST";
export const EVENTSECOND_ADDED_SUCCESS="EVENTSECOND_ADDED_SUCCESS";
export const EVENTSECOND_ADDED_FAIL="EVENTSECOND_ADDED_FAIL";
export const EVENTSECOND_REMOVE="EVENTSECOND_REMOVE";