export const REVIEW_ADDED_REQUEST="REVIEW_ADDED_REQUEST";
export const REVIEW_ADDED_SUCCESS="REVIEW_ADDED_SUCCESS";
export const REVIEW_ADDED_FAIL="REVIEW_ADDED_FAIL";
export const REVIEW_REMOVE="REVIEW_REMOVE";
