export const STUDENT_ADDED_REQUEST="STUDENT_ADDED_REQUEST";
export const STUDENT_ADDED_SUCCESS="STUDENT_ADDED_SUCCESS";
export const STUDENT_ADDED_FAIL="STUDENT_ADDED_FAIL";
export const STUDENT_REMOVE="STUDENT_REMOVE";