export const TEACHER_ADDED_REQUEST="TEACHER_ADDED_REQUEST";
export const TEACHER_ADDED_SUCCESS="TEACHER_ADDED_SUCCESS";
export const TEACHER_ADDED_FAIL="TEACHER_ADDED_FAIL";
export const TEACHER_REMOVE="TEACHER_REMOVE";
